version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Standard build
          command: cargo build
      - run:
          name: Cargo tests
          command: cargo test
