version: 2
jobs:
  build:
    docker:
      - image: nicolaspolomack/debian-rust
    working_directory: /build/epitech-api-rs
    steps:
      - checkout:
          path: /build
      - run:
          name: Standard build
          command: cargo build
      # - run:
      #     name: Cargo tests
      #     command: cargo test
