name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --bins --examples

    - name: check unstable
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --benches --bins --examples --tests

    - name: tests
      uses: actions-rs/cargo@v1
      env:
        EPITECH_AUTOLOGIN: ${{ secrets.EPITECH_AUTOLOGIN }}
      with:
        command: test
        args: --all
